MarketProspection/Controllers/UpworkSuivisController.cs
using MarketProspection.Data;
using MarketProspection.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MarketProspection.Controllers
{
    public class UpworkSuivisController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UpworkSuivisController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UpworkSuivis
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.UpworkSuivis
                .Include(u => u.PricingType)
                .Include(u => u.ProjectLength)
                .Include(u => u.SubmittingProfile)
                .Include(u => u.Technology)
                .OrderByDescending(e => e.Id) // Assuming there is an Id property for ordering
                .Take(10);


            ViewBag.rbopen = "menu-open";
            ViewBag.rb = "active";
            ViewBag.rbrcpt = "active";

            return View(await applicationDbContext.ToListAsync());
        }


        public async Task<IActionResult> GetAll()
        {
            var applicationDbContext = _context.UpworkSuivis
                .Include(u => u.PricingType)
                .Include(u => u.ProjectLength)
                .Include(u => u.SubmittingProfile)
                .Include(u => u.Technology);

            ViewBag.rbopen = "menu-open";
            ViewBag.rb = "active";
            ViewBag.rbrcpt = "active";

            return View(await applicationDbContext.ToListAsync());
        }



        // GET: UpworkSuivis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UpworkSuivis == null)
            {
                return NotFound();
            }

            var upworkSuivi = await _context.UpworkSuivis
                .Include(u => u.PricingType)
                .Include(u => u.ProjectLength)
                .Include(u => u.SubmittingProfile)
                .Include(u => u.Technology)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (upworkSuivi == null)
            {
                return NotFound();
            }


            ViewBag.rbopen = "menu-open";
            ViewBag.rb = "active";
            ViewBag.rbrcpt = "active";

            return View(upworkSuivi);
        }

        // GET: UpworkSuivis/Create
        public IActionResult Create()
        {
            ViewData["PricingTypeId"] = new SelectList(_context.PricingTypes, "Id", "Pricingtype");
            ViewData["ProjectLengthId"] = new SelectList(_context.ProjectLengths, "Id", "Length");
            ViewData["SubmittingProfileId"] = new SelectList(_context.SubmittingProfiles, "Id", "Profile");
            ViewData["TechnologyId"] = new SelectList(_context.Technologies, "Id", "TechnologyName");


            ViewBag.rbopen = "menu-open";
            ViewBag.rb = "active";
            ViewBag.rbsrt = "active";



            return View();
        }

        // POST: UpworkSuivis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProposalDate,JobTitle,RequiredConnects,Bid,ProjectLengthId,PricingTypeId,ClientPricing,Pricing,SubmittingProfileId,JobLink,TechnologyId,Viewed,ViewDate,Response,ResponseDate,Interview,InterviewDate,Hired,HireDate")] UpworkSuivi upworkSuivi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(upworkSuivi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PricingTypeId"] = new SelectList(_context.PricingTypes, "Id", "Id", upworkSuivi.PricingTypeId);
            ViewData["ProjectLengthId"] = new SelectList(_context.ProjectLengths, "Id", "Id", upworkSuivi.ProjectLengthId);
            ViewData["SubmittingProfileId"] = new SelectList(_context.SubmittingProfiles, "Id", "Id", upworkSuivi.SubmittingProfileId);
            ViewData["TechnologyId"] = new SelectList(_context.Technologies, "Id", "Id", upworkSuivi.TechnologyId);


            ViewBag.rbopen = "menu-open";
            ViewBag.rb = "active";
            ViewBag.rbrcpt = "rbsrt";

            return View(upworkSuivi);
        }

        // GET: UpworkSuivis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UpworkSuivis == null)
            {
                return NotFound();
            }

            var upworkSuivi = await _context.UpworkSuivis.FindAsync(id);
            if (upworkSuivi == null)
            {
                return NotFound();
            }
            ViewData["PricingTypeId"] = new SelectList(_context.PricingTypes, "Id", "Id", upworkSuivi.PricingTypeId);
            ViewData["ProjectLengthId"] = new SelectList(_context.ProjectLengths, "Id", "Id", upworkSuivi.ProjectLengthId);
            ViewData["SubmittingProfileId"] = new SelectList(_context.SubmittingProfiles, "Id", "Id", upworkSuivi.SubmittingProfileId);
            ViewData["TechnologyId"] = new SelectList(_context.Technologies, "Id", "Id", upworkSuivi.TechnologyId);


            ViewBag.rbopen = "menu-open";
            ViewBag.rb = "active";
            ViewBag.rbrcpt = "active";


            return View(upworkSuivi);
        }

        // POST: UpworkSuivis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProposalDate,JobTitle,RequiredConnects,Bid,ProjectLengthId,PricingTypeId,ClientPricing,Pricing,SubmittingProfileId,JobLink,TechnologyId,Viewed,ViewDate,Response,ResponseDate,Interview,InterviewDate,Hired,HireDate")] UpworkSuivi upworkSuivi)
        {
            if (id != upworkSuivi.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(upworkSuivi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UpworkSuiviExists(upworkSuivi.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PricingTypeId"] = new SelectList(_context.PricingTypes, "Id", "Id", upworkSuivi.PricingTypeId);
            ViewData["ProjectLengthId"] = new SelectList(_context.ProjectLengths, "Id", "Id", upworkSuivi.ProjectLengthId);
            ViewData["SubmittingProfileId"] = new SelectList(_context.SubmittingProfiles, "Id", "Id", upworkSuivi.SubmittingProfileId);
            ViewData["TechnologyId"] = new SelectList(_context.Technologies, "Id", "Id", upworkSuivi.TechnologyId);


            ViewBag.rbopen = "menu-open";
            ViewBag.rb = "active";
            ViewBag.rbrcpt = "active";


            return View(upworkSuivi);
        }

        // GET: UpworkSuivis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UpworkSuivis == null)
            {
                return NotFound();
            }

            var upworkSuivi = await _context.UpworkSuivis
                .Include(u => u.PricingType)
                .Include(u => u.ProjectLength)
                .Include(u => u.SubmittingProfile)
                .Include(u => u.Technology)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (upworkSuivi == null)
            {
                return NotFound();
            }

            ViewBag.rbopen = "menu-open";
            ViewBag.rb = "active";
            ViewBag.rbrcpt = "active";

            return View(upworkSuivi);
        }

        // POST: UpworkSuivis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UpworkSuivis == null)
            {
                return Problem("Entity set 'ApplicationDbContext.UpworkSuivis'  is null.");
            }
            var upworkSuivi = await _context.UpworkSuivis.FindAsync(id);
            if (upworkSuivi != null)
            {
                _context.UpworkSuivis.Remove(upworkSuivi);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UpworkSuiviExists(int id)
        {
            return _context.UpworkSuivis.Any(e => e.Id == id);
        }
    }
}

MarketProspection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarketProspection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarketProspection.styles.css" asp-append-version="true" />
    
    
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">

    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">

    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    

    <!-- Theme style -->
    @*<link rel="stylesheet" href="~/dist/css/adminlte.min.css">*@
    
    
    
    
    
    
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">

    

</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed ">




<div class="wrapper">

    <nav class="main-header navbar navbar-expand navbar-white navbar-light">

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
   
        </ul>
    
    
    
        <ul class="navbar-nav ml-auto">
            <!-- Navbar Search -->
            <li class="nav-item">

                <partial name="_LoginPartial" />
            </li>

    
        </ul>
    </nav>


    <partial name="_Menu" />
    
  
    <div class="content-wrapper">
        <section class="content">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </section>
    </div>



</div>







<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>









<script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/plugins/jszip/jszip.min.js"></script>
<script src="~/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="~/dist/js/adminlte.js"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="~/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MarketProspection/Views/Shared/_Menu.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a asp-area="" asp-controller="Home" asp-action="Index" class="brand-link">
        <img src="~/dist/img/skaalab2.png" alt="AdminLTE Logo" class="brand-image" style="opacity: .8">
        @*<span class="brand-text font-weight-light">SAFHADID</span>*@
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">@User.Identity.Name</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

              


                <li class="nav-item @ViewBag.rbopen">
                    <a href="#" class="nav-link @ViewBag.rb">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Upwork
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="UpworkSuivis" asp-action="Create" class="nav-link @ViewBag.rbsrt">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Nouvelle entrée</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="UpworkSuivis" asp-action="Index" class="nav-link @ViewBag.rbrcpt">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Lister</p>
                            </a>
                        </li>

                    </ul>
                </li>








            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>